name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.go/pkg/mod
            ~/.go/pkg/dep/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go mod download
        run: |
          go mod download

      - name: Run SAST
        uses: semgrep-action@v1

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0

      - name: Build the binary
        run: |
          go build -o ./bin/app .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./bin/app
