name: Trigger Deployment

on:
  repository_dispatch:
    types: [ deploy ]

jobs:
  trigger_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow
        uses: robinst/trigger-workflow@v3
        with:
          repo: teopasc/go-webapp-deployment # Replace with your repository
          workflow: containerize # Name of the workflow in the deployment repo
          ref: main 
