name: Trigger Deployment

on:
  repository_dispatch:
    types: [ deploy ]

jobs:
  trigger_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow
        uses: robinst/trigger-workflow@v3
        with:
          repo: docker.io/teopascalev/go-web-project
          workflow: Containerize
          ref: main 
