name: Release

on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.go/pkg/mod
            ~/.go/pkg/dep/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go mod download
        run: |
          go mod download

      - name: Run SAST (semgrep)
        uses: chainguard/action-semgrep@v4

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0 # Use a specific version for reproducibility

      - name: Build the binary
        run: |
          go build -o ./bin/app .

      - name: Upload release asset
        uses: actions/upload-release-asset@v3
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This will be set by the create_release step
          asset_path: ./bin/app
          asset_name: app-${{ github.run_id }}-${{ github.sha }}.exe 
